### ISSUE TITLE
Django-filer renders incorrectly in admin site

### ISSUE THREAD

**Issue by an0o0nym** [django-cms/django-filer#905]
After following the  installation instructions on django-filer docs website, I started the development server on my local machine and tested out if everything works. However when I open django admin site and click on filer folders, I can see that the form is not rendering correctly. The whole `#content` div is aligned to the right site, and the `.breadcrumbs-container-inner` is a mess. I am using Django 1.9.8 and Django-filer 1.2.4. I attach screen shots of what I get.(Full-window size, and small size window). Is that a bug of django-filer? Can anyone reproduce the problem, or have had similar problems in the past? How can I fix this?
![Screenshot #1](http://i.imgur.com/32Gjbop.png)
![Screenshot #2](http://i.imgur.com/kaJWwvI.png)

**Comment by benzkji** [comment]
this looks like django-admin-tools, but broken? I thought django-admin-tools is not a dependency of django-file (it's not mentioned in the docs?). But maybe it became one. Honestly, I've not used filer without admin-tools for a while. But what I would expect, is something more close to the default django admin.

**Comment by an0o0nym** [comment]
@benzkji Thanks for your reply!

I do not have django-admin-tools installed. Every section of django admin works fine, except the django-filer one. I tried to install django-admin-tools hoping it may fix the problem somehow, however it did not. I think it's related to the styling of django-filer, but I am not really that much into CSS.

**Comment by benzkji** [comment]
sorry, mispelled, it's `djangocms-admin-style`!

**Comment by ohrstrom** [comment]
We did came across this display issue as well. Using the same versions of Django and django-filer as @an0o0nym - in a fresh project with just `filer` as additional app.  
When adding `djangocms-admin-style` however the folder listing (header) displays correctly.

**Comment by an0o0nym** [comment]
@benzkji @ohrstrom You were right, after installing djangocms-admin-style the problem is gone! Thanks a lot for support! 

Rookie question, should I wait until there is a commit(which solves this issue)that is merged into the django-filer repository? Or should I close this issue?
@benzkji @ohrstrom You were right, after installing djangocms-admin-style the problem is gone! Thanks a lot for support! 

Rookie question, should I wait until there is a commit(which solves this issue)that is merged into the django-filer repository? Or should I close this issue?

**Comment by benzkji** [comment]
@an0o0nym not so easy. depends wether filer is also supported to be used without djangocms-admin-style (what docs suggest), or if this will be a dependency. an oppinion from @mkoistinen may help.
-
in general, the situation as it's currently is not so good, because filer really changes the way the admin looks, but only for himself. without admin tools, it should look like the normal django admin.

**Comment by an0o0nym** [comment]
@benzkji, you made it clear now. 

Introducing ``djangocms-admin-style`` as a filer's dependency might not be the best idea. As you mentioned - filer changes, but only for himself,  the way the admin interface looks - however ``djangocms-admin-style`` changes the look of the whole admin interface, which is not what most people would like to do. @metaforx lately added a patch which references this issue - hopefully this will do the job.

Thanks a lot for your time and the feedback, I really appreciate it !

**Comment by wiesson** [comment]
@an0o0nym I'm using django-filer (without django-cms) and I always wondered, why the styles are broken. Can I use ```djangocms-admin-style``` without django-cms?

**Comment by benzkji** [comment]
@wiesson yes you can.

**Comment by ifishlin** [comment]
Here, I have a trivial rendering problem, and would like to know how to solve it.
When I used django-suit with django-filer, there are a shift between main and title block in Filer page. (red)

![default](https://cloud.githubusercontent.com/assets/9721827/20028391/21ba542e-a36b-11e6-9b48-aaa3df52bccc.png)

django-filer (1.2.5)
djangocms-admin-style (1.2.5)
suit (2.0.2)

Does anyone have idea how to solve it? thanks

**Comment by bhrutledge** [comment]
I'm also trying to use django-filer without djangocms-admin-style, and have encountered UI bugs similar to the original post. In the short term, I think djangocms-admin-style should listed as a dependency. But, that brings up a question for the maintainers: is that the intention? IE, should django-filer be fully functional without djangocms-admin-style? If so, then I'm guessing you would welcome PR's to break the dependency.

**Comment by yakky** [comment]
This should be fixed by #934

**Comment by bhrutledge** [comment]
Thanks for the update, but I'm still getting UI bugs, most noticeably around the search field.

1.8:
![filer_1_8](https://cloud.githubusercontent.com/assets/1326704/20152459/5337edb2-a68c-11e6-87d0-9c08917108bd.gif)

1.9:
![filer_1_9](https://cloud.githubusercontent.com/assets/1326704/20152444/3fec70e8-a68c-11e6-9340-7d5f8ca695f7.gif)

These are from a fresh Django `startproject`, followed by `pip install django-filer` and adding the entries to `INSTALLED_APPS`.

**Comment by yakky** [comment]
@FinalAngel @vxsx could you have a look at the screencasts above?

**Comment by wiesson** [comment]
I also would like to use django-filer without djangocms-admin-style.

**Comment by FinalAngel** [comment]
#934 just fixed the compilation of the css file which makes filer look a bit better. Though I won't be able to touch filer again soon to fix it, I'd welcome the community to submit a pull request 👍

**Comment by Nomados** [comment]
I still have the exactly same issue with Django 1.11
